# Week 3 Lecture Chapter 6 - Tables

[datascience reference website](https://www.data8.org/datascience/reference-nb/datascience-reference.html)

Run the code cell below

In [73]:
from datascience import *
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')
import warnings
warnings.simplefilter(action="ignore", category=FutureWarning)

from urllib.request import urlopen 
import re
def read_url(url): 
    return re.sub('\\s+', ' ', urlopen(url).read().decode())

# Table
```
Table()  # Empty Table
```
Add columns to Table
```
Table().with_columns('Column_name1', make_array(value1, value2, value3....),
                    )
# Adding columns to Table
```

In [74]:
# Create a Table with column Number of petals with values 8, 34, 5
Table().with_columns('Number of petals', make_array(8, 34, 5))

Number of petals
8
34
5

In [75]:
# Add two new columns use the table command above and add Name 
# make_array('lotus', 'Sunflower', 'Rose')
Table().with_columns('Number of petals', make_array(8, 34, 5),
                    'Name', make_array('Lotus','Sunflower', 'Rose')
                    )

Number of petals | Name
8                | Lotus
34               | Sunflower
5                | Rose

In [76]:
# Assign the table to a variable
flowers = Table().with_columns('Number of petals', make_array(8, 34, 5),
                    'Name', make_array('Lotus','Sunflower', 'Rose')
                    )

In [77]:
# Add a new column to the table
flowers.with_columns('Color', make_array('pink','yellow','red'))

Number of petals | Name      | Color
8                | Lotus     | pink
34               | Sunflower | yellow
5                | Rose      | red

In [78]:
# it did not add a column to the flowers table
flowers

Number of petals | Name
8                | Lotus
34               | Sunflower
5                | Rose

# Reading a Comma Separated Table
```
table_name = Table().read_table(path+'filename.csv')
```
In your case the file will be in the same folder as your Week 3 Lecture Jupter Notebook.

|Column 	|Data Type	| Description  |
Longitude	Numeric	    The longitude of the army's position.<br>
Latitude	Numeric	    The latitude of the army's position.<br>
Survivors	Numeric	    The estimated number of surviving troops at that  <br>                                location.<br>
Direction	Categorical	Indicates the direction of the army's travel, with <br>levels like "Advance" and "Retreat".<br>
City	Categorical	The name of the nearest city. This column might sometimes<br> be found in a separate cities.csv file.<br>

In [79]:
# read minard.csv file into minard variable and display it
# minard is a data set that shows the number of survivors Napoleon's disastrous Russian
# campaign of 1812–1813
minard = Table().read_table('minard.csv')
minard

Longitude | Latitude | City        | Direction | Survivors
32        | 54.8     | Smolensk    | Advance   | 145000
33.2      | 54.9     | Dorogobouge | Advance   | 140000
34.4      | 55.5     | Chjat       | Advance   | 127100
37.6      | 55.8     | Moscou      | Advance   | 100000
34.3      | 55.2     | Wixma       | Retreat   | 55000
32        | 54.6     | Smolensk    | Retreat   | 24000
30.4      | 54.4     | Orscha      | Retreat   | 20000
26.8      | 54.3     | Moiodexno   | Retreat   | 12000

# Size of the Table 
Sometimes we want to know the number of rows, the number of columns, and the size of a table.
```
table_name.num_columns
table_name.num_rows
```

In [80]:
minard.num_columns

5

In [81]:
minard.num_rows

8

# Column Labels
When we want to know the column names in a table we can use the labels method.  It will create an array of the column names.
```
table_name.labels
```

In [82]:
# List the column in the minard table
minard.labels

('Longitude', 'Latitude', 'City', 'Direction', 'Survivors')

# Change the column name
```
table_name.relabeled('old_name', 'new_name')
```
If you do not assign minard relabeled state to minard it will not change the table.

In [83]:
# rename the City to City Name
minard.relabeled('City', 'City Name')

Longitude | Latitude | City Name   | Direction | Survivors
32        | 54.8     | Smolensk    | Advance   | 145000
33.2      | 54.9     | Dorogobouge | Advance   | 140000
34.4      | 55.5     | Chjat       | Advance   | 127100
37.6      | 55.8     | Moscou      | Advance   | 100000
34.3      | 55.2     | Wixma       | Retreat   | 55000
32        | 54.6     | Smolensk    | Retreat   | 24000
30.4      | 54.4     | Orscha      | Retreat   | 20000
26.8      | 54.3     | Moiodexno   | Retreat   | 12000

In [84]:
# display table
minard

Longitude | Latitude | City        | Direction | Survivors
32        | 54.8     | Smolensk    | Advance   | 145000
33.2      | 54.9     | Dorogobouge | Advance   | 140000
34.4      | 55.5     | Chjat       | Advance   | 127100
37.6      | 55.8     | Moscou      | Advance   | 100000
34.3      | 55.2     | Wixma       | Retreat   | 55000
32        | 54.6     | Smolensk    | Retreat   | 24000
30.4      | 54.4     | Orscha      | Retreat   | 20000
26.8      | 54.3     | Moiodexno   | Retreat   | 12000

In [85]:
# assign new column name to minard table
minard = minard.relabeled('City', 'City Name')

In [86]:
# display minard
minard

Longitude | Latitude | City Name   | Direction | Survivors
32        | 54.8     | Smolensk    | Advance   | 145000
33.2      | 54.9     | Dorogobouge | Advance   | 140000
34.4      | 55.5     | Chjat       | Advance   | 127100
37.6      | 55.8     | Moscou      | Advance   | 100000
34.3      | 55.2     | Wixma       | Retreat   | 55000
32        | 54.6     | Smolensk    | Retreat   | 24000
30.4      | 54.4     | Orscha      | Retreat   | 20000
26.8      | 54.3     | Moiodexno   | Retreat   | 12000

# Accessing the data in a column
To change the data in a column to an array we use the column method.
```
table_name.column('column_name')
```

In [87]:
# Access the Survivors using the column method
minard.column('Survivors')

array([145000, 140000, 127100, 100000,  55000,  24000,  20000,  12000])

In [88]:
# columns in the table are index starting with 0 so the 4 column is the Survivors column.
minard.column(4)

array([145000, 140000, 127100, 100000,  55000,  24000,  20000,  12000])

In [89]:
# item will access a specific value in the array - index starts at 0
# display the first item
minard.column(4).item(0)

145000

In [90]:
# display the last item
minard.column(4).item(7)

12000

# Calculation with arrays
Working with data in a column.  Last week we showed how to do calculations with arrays.

In [91]:
# create a variable with the first element of the Survivor array
# Calculate the percent survivors
initial = minard.column('Survivors').item(0)
minard = minard.with_columns(
    'Percent Surviving', minard.column('Survivors')/initial
)
minard

Longitude | Latitude | City Name   | Direction | Survivors | Percent Surviving
32        | 54.8     | Smolensk    | Advance   | 145000    | 1
33.2      | 54.9     | Dorogobouge | Advance   | 140000    | 0.965517
34.4      | 55.5     | Chjat       | Advance   | 127100    | 0.876552
37.6      | 55.8     | Moscou      | Advance   | 100000    | 0.689655
34.3      | 55.2     | Wixma       | Retreat   | 55000     | 0.37931
32        | 54.6     | Smolensk    | Retreat   | 24000     | 0.165517
30.4      | 54.4     | Orscha      | Retreat   | 20000     | 0.137931
26.8      | 54.3     | Moiodexno   | Retreat   | 12000     | 0.0827586

# Formatting the columns
we talked about formatting columns last week.  We will continue talking about formatting columns.

**Types of Column Formatter**
- PercentFormatter
- DateFormatter
- CurrencyFormatter

```
table_name.set_format('column name', type of Column Formatter)
```

In [92]:
minard.set_format('Percent Surviving', PercentFormatter)

Longitude | Latitude | City Name   | Direction | Survivors | Percent Surviving
32        | 54.8     | Smolensk    | Advance   | 145000    | 100.00%
33.2      | 54.9     | Dorogobouge | Advance   | 140000    | 96.55%
34.4      | 55.5     | Chjat       | Advance   | 127100    | 87.66%
37.6      | 55.8     | Moscou      | Advance   | 100000    | 68.97%
34.3      | 55.2     | Wixma       | Retreat   | 55000     | 37.93%
32        | 54.6     | Smolensk    | Retreat   | 24000     | 16.55%
30.4      | 54.4     | Orscha      | Retreat   | 20000     | 13.79%
26.8      | 54.3     | Moiodexno   | Retreat   | 12000     | 8.28%

# Selecting columns 
We talked about selecting columns using the select method.
```
table_name.select('column_name1', 'column_name2', etc.)
table_name.select(index_column1, index_column2, etc.)
```

In [93]:
# display columns Longitude and Latitude
minard.select('Longitude','Latitude')

Longitude | Latitude
32        | 54.8
33.2      | 54.9
34.4      | 55.5
37.6      | 55.8
34.3      | 55.2
32        | 54.6
30.4      | 54.4
26.8      | 54.3

In [94]:
# display columns Longitude and Latitude using indes
minard.select(0,1)

Longitude | Latitude
32        | 54.8
33.2      | 54.9
34.4      | 55.5
37.6      | 55.8
34.3      | 55.2
32        | 54.6
30.4      | 54.4
26.8      | 54.3

In [95]:
# display Survivors columns
minard.select('Survivors')

Survivors
145000
140000
127100
100000
55000
24000
20000
12000

In [96]:
# put the column Survivors in an array using the column method
minard.column('Survivors')

array([145000, 140000, 127100, 100000,  55000,  24000,  20000,  12000])

# Drop Method
To drop columns you don't want use the drop method.  It does not change the table unless you assign it to the original table.
```
table_name.drop('colun_name1', 'column_name2')
```

In [97]:
# Drop Longitude, Latitude, and Direction
minard.drop('Longitude', 'Latitude', 'Direction')

City Name   | Survivors | Percent Surviving
Smolensk    | 145000    | 100.00%
Dorogobouge | 140000    | 96.55%
Chjat       | 127100    | 87.66%
Moscou      | 100000    | 68.97%
Wixma       | 55000     | 37.93%
Smolensk    | 24000     | 16.55%
Orscha      | 20000     | 13.79%
Moiodexno   | 12000     | 8.28%

In [98]:
# display minard
minard

Longitude | Latitude | City Name   | Direction | Survivors | Percent Surviving
32        | 54.8     | Smolensk    | Advance   | 145000    | 100.00%
33.2      | 54.9     | Dorogobouge | Advance   | 140000    | 96.55%
34.4      | 55.5     | Chjat       | Advance   | 127100    | 87.66%
37.6      | 55.8     | Moscou      | Advance   | 100000    | 68.97%
34.3      | 55.2     | Wixma       | Retreat   | 55000     | 37.93%
32        | 54.6     | Smolensk    | Retreat   | 24000     | 16.55%
30.4      | 54.4     | Orscha      | Retreat   | 20000     | 13.79%
26.8      | 54.3     | Moiodexno   | Retreat   | 12000     | 8.28%

In [99]:
# 2015-2016 NBA 
nba_salaries = Table.read_table('NBA_SALARIES2015.csv')
nba_salaries.show()

# Relabel columns
```
table_name.relabeled('old_name', 'new_name')
```

In [100]:
# change 'SALARY ($M)' TO 'SALARY'
nba = nba_salaries.relabeled('SALARY ($M)', 'SALARY')

# Sorting Rows
Sorting rows
```
table_name.sort('column_name')  # ascending
table_name.sort('column_name', descending = True) # descending
```

In [101]:
# Sort by SALARY column
nba.sort('SALARY')

RANK | PLAYER                 | POSITION | TEAM              | SALARY
417  | Thanasis Antetokounmpo | SF       | New York Knicks   | 0.030888
415  | Jordan McRae           | SG       | Phoenix Suns      | 0.049709
416  | Cory Jefferson         | PF       | Phoenix Suns      | 0.049709
412  | Orlando Johnson        | SG       | Phoenix Suns      | 0.055722
413  | Elliot Williams        | SG       | Memphis Grizzlies | 0.055722
414  | Phil Pressey           | PG       | Phoenix Suns      | 0.055722
411  | Keith Appling          | PG       | Orlando Magic     | 0.061776
409  | Erick Green            | PG       | Utah Jazz         | 0.099418
410  | Sean Kilpatrick        | SG       | Denver Nuggets    | 0.099418
406  | Lorenzo Brown          | PG       | Phoenix Suns      | 0.111444
... (406 rows omitted)

In [102]:
# sort descending
nba.sort('SALARY',descending=True)

RANK | PLAYER            | POSITION | TEAM                  | SALARY
1    | Kobe Bryant       | SF       | Los Angeles Lakers    | 25
2    | Joe Johnson       | SF       | Brooklyn Nets         | 24.8949
3    | LeBron James      | SF       | Cleveland Cavaliers   | 22.9705
4    | Carmelo Anthony   | SF       | New York Knicks       | 22.875
5    | Dwight Howard     | C        | Houston Rockets       | 22.3594
6    | Chris Bosh        | PF       | Miami Heat            | 22.1927
7    | Chris Paul        | PG       | Los Angeles Clippers  | 21.4687
8    | Kevin Durant      | SF       | Oklahoma City Thunder | 20.1586
9    | Derrick Rose      | PG       | Chicago Bulls         | 20.0931
11   | LaMarcus Aldridge | PF       | San Antonio Spurs     | 19.689
... (406 rows omitted)

# Help on functions

```
help(table_name.method)
```

In [103]:
# use the help command to find out about sorting
help(nba.sort)

Help on method sort in module datascience.tables:

sort(column_or_label, descending=False, distinct=False) method of datascience.tables.Table instance
    Return a Table of rows sorted according to the values in a column.

    Args:
        ``column_or_label``: the column whose values are used for sorting.

        ``descending``: if True, sorting will be in descending, rather than
            ascending order.

        ``distinct``: if True, repeated values in ``column_or_label`` will
            be omitted.

    Returns:
        An instance of ``Table`` containing rows sorted based on the values
        in ``column_or_label``.

    >>> marbles = Table().with_columns(
    ...    "Color", make_array("Red", "Green", "Blue", "Red", "Green", "Green"),
    ...    "Shape", make_array("Round", "Rectangular", "Rectangular", "Round", "Rectangular", "Round"),
    ...    "Amount", make_array(4, 6, 12, 7, 9, 2),
    ...    "Price", make_array(1.30, 1.30, 2.00, 1.75, 1.40, 1.00))
    >>> marbles
    Color | Shape       | Amount | Price
    Red   | Round       | 4      | 1.3
    Green | Rectangular | 6      | 1.3
    Blue  | Rectangular | 12     | 2
    Red   | Round       | 7      | 1.75
    Green | Rectangular | 9      | 1.4
    Green | Round       | 2      | 1
    >>> marbles.sort("Amount")
    Color | Shape       | Amount | Price
    Green | Round       | 2      | 1
    Red   | Round       | 4      | 1.3
    Green | Rectangular | 6      | 1.3
    Red   | Round       | 7      | 1.75
    Green | Rectangular | 9      | 1.4
    Blue  | Rectangular | 12     | 2
    >>> marbles.sort("Amount", descending = True)
    Color | Shape       | Amount | Price
    Blue  | Rectangular | 12     | 2
    Green | Rectangular | 9      | 1.4
    Red   | Round       | 7      | 1.75
    Green | Rectangular | 6      | 1.3
    Red   | Round       | 4      | 1.3
    Green | Round       | 2      | 1
    >>> marbles.sort(3) # the Price column
    Color | Shape       | Amount | Price
    Green | Round       | 2      | 1
    Red   | Round       | 4      | 1.3
    Green | Rectangular | 6      | 1.3
    Green | Rectangular | 9      | 1.4
    Red   | Round       | 7      | 1.75
    Blue  | Rectangular | 12     | 2
    >>> marbles.sort(3, distinct = True)
    Color | Shape       | Amount | Price
    Green | Round       | 2      | 1
    Red   | Round       | 4      | 1.3
    Green | Rectangular | 9      | 1.4
    Red   | Round       | 7      | 1.75
    Blue  | Rectangular | 12     | 2

In [104]:
nba.sort('SALARY', distinct=True)

RANK | PLAYER                 | POSITION | TEAM                  | SALARY
417  | Thanasis Antetokounmpo | SF       | New York Knicks       | 0.030888
415  | Jordan McRae           | SG       | Phoenix Suns          | 0.049709
412  | Orlando Johnson        | SG       | Phoenix Suns          | 0.055722
411  | Keith Appling          | PG       | Orlando Magic         | 0.061776
409  | Erick Green            | PG       | Utah Jazz             | 0.099418
406  | Lorenzo Brown          | PG       | Phoenix Suns          | 0.111444
405  | Bryce Dejean-Jones     | SG       | New Orleans Pelicans  | 0.169883
404  | JaKarr Sampson         | SG       | Philadelphia 76ers    | 0.258489
402  | Steve Novak            | SF       | Oklahoma City Thunder | 0.289755
389  | Greg Whittington       | SF       | Miami Heat            | 0.525093
... (303 rows omitted)

In [105]:
nba

RANK | PLAYER            | POSITION | TEAM                  | SALARY
1    | Kobe Bryant       | SF       | Los Angeles Lakers    | 25
2    | Joe Johnson       | SF       | Brooklyn Nets         | 24.8949
3    | LeBron James      | SF       | Cleveland Cavaliers   | 22.9705
4    | Carmelo Anthony   | SF       | New York Knicks       | 22.875
5    | Dwight Howard     | C        | Houston Rockets       | 22.3594
6    | Chris Bosh        | PF       | Miami Heat            | 22.1927
7    | Chris Paul        | PG       | Los Angeles Clippers  | 21.4687
8    | Kevin Durant      | SF       | Oklahoma City Thunder | 20.1586
9    | Derrick Rose      | PG       | Chicago Bulls         | 20.0931
11   | LaMarcus Aldridge | PF       | San Antonio Spurs     | 19.689
... (406 rows omitted)

# Using the take to select a row
```
table_name.take(index_number1, index_number2, etc.)  # index start at 0
```
This is a new table with subset of records based on the indexes listed.

In [106]:
# display the first row
nba.take(0)

RANK | PLAYER      | POSITION | TEAM               | SALARY
1    | Kobe Bryant | SF       | Los Angeles Lakers | 25

In [107]:
nba.take(np.arange(3,6))

RANK | PLAYER          | POSITION | TEAM            | SALARY
4    | Carmelo Anthony | SF       | New York Knicks | 22.875
5    | Dwight Howard   | C        | Houston Rockets | 22.3594
6    | Chris Bosh      | PF       | Miami Heat      | 22.1927

# Combining methods
```
table_name.sort('column_name').take(np.arange(n))
```

In [108]:
# display top 5 highest paid players
nba.sort('SALARY', descending=True).take(np.arange(5))

RANK | PLAYER          | POSITION | TEAM                | SALARY
1    | Kobe Bryant     | SF       | Los Angeles Lakers  | 25
2    | Joe Johnson     | SF       | Brooklyn Nets       | 24.8949
3    | LeBron James    | SF       | Cleveland Cavaliers | 22.9705
4    | Carmelo Anthony | SF       | New York Knicks     | 22.875
5    | Dwight Howard   | C        | Houston Rockets     | 22.3594

So far we've only been using `where` with the predicate that requires finding the values in a column to be *exactly* equal to a certain value. However, there are many other predicates. Here are a few:

|Predicate|Example|Result|
|-|-|-|
|`are.equal_to`|`are.equal_to(50)`|Find rows with values equal to 50|
|`are.not_equal_to`|`are.not_equal_to(50)`|Find rows with values not equal to 50|
|`are.above`|`are.above(50)`|Find rows with values above (and not equal to) 50|
|`are.above_or_equal_to`|`are.above_or_equal_to(50)`|Find rows with values above 50 or equal to 50|
|`are.below`|`are.below(50)`|Find rows with values below 50|
|`are.between`|`are.between(2, 10)`|Find rows with values above or equal to 2 and below 10|
|`are.between_or_equal_to`|`are.between_or_equal_to(2, 10)`|Find rows with values above or equal to 2 and below or equal to 10|

In [109]:
# records with SALARY above 10 million

In [110]:
# salary above 10 million then sorted in ascending order

In [111]:
# records with PLAYER 'Stephen Curry'

In [112]:
# records with Golden State Warriors

In [113]:
# records with Team Denver Nuggets

In [ ]:
# Point Guard with salary above 15 million

In [ ]:
# salary between 10 and less than 10.3

In [ ]:
# Player Barack Obama

In [ ]:
# records containing Warriors

In [114]:
# records position contains G

In [ ]:
# not Clevland Cavaliers  with salary no less than 20 million