# Week 5 Lecture 
This week we will cover the following topics
- Histograms
- Groups
- Pivots and Joins
- Functions
- Application to a column

First run the code cell below.

In [1]:
from datascience import *
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')
import warnings
warnings.simplefilter(action="ignore", category=FutureWarning)

from urllib.request import urlopen 
import re
def read_url(url): 
    return re.sub('\\s+', ' ', urlopen(url).read().decode())

In [41]:
# read in data
nba = Table.read_table('nba_salaries.csv').where('season',are.equal_to(2015))
nba

rank | name            | position | team                  | salary   | season
1    | Kobe Bryant     | SF       | Los Angeles Lakers    | 23500000 | 2015
2    | Joe Johnson     | G        | Brooklyn Nets         | 23180790 | 2015
3    | Carmelo Anthony | PF       | New York Knicks       | 22458401 | 2015
4    | Dwight Howard   | C        | Houston Rockets       | 21436271 | 2015
5    | Chris Bosh      | PF       | Miami Heat            | 20644400 | 2015
6    | LeBron James    | SF       | Cleveland Cavaliers   | 20644400 | 2015
7    | Chris Paul      | PG       | LA Clippers           | 20068563 | 2015
8    | Deron Williams  | PG       | Brooklyn Nets         | 19754465 | 2015
9    | Rudy Gay        | SF       | Sacramento Kings      | 19317326 | 2015
10   | Kevin Durant    | SF       | Oklahoma City Thunder | 18995624 | 2015
... (517 rows omitted)

# Functions
A small snippet of code that can be used over and over again.  

```
def function_name(x):
    """Description of function"""
    return y
```
You must first define the function before you use it.  Give it a name that describes what it does then within the function describe what it does.  This helps others who view your function understand what it does or you forget it is a reminder.<br>

Write a function that multiples a number by 7 and return that value in one code cell.  Then run it for the x values of 3, 6, 9 in other code cell.

In [9]:
# define a function calculate the agent pay

21

42

63

# Applying a function to a column of a Table
Sometimes we need apply a function to each value of a column of a table.  You would use the method apply.  Suppose you have a function called scale_it.  You want to apply it to a column of the table this would be the format.
```
table_name.apply(function_name, 'column_name')
```
Create a table calle ages like the one in the textbook.  Then create a function call project_years to determine years of service to retirement.  Apply it to the Age column and display it.

# Single Grouping
To group by a single variable you use the group method and one the functions to summarize the data.
```
table_name.group('column_name')  # displays the counts in each group
    
table_name.group('column_name', sum)        # built-in function
    
table_name.group('column_name', len)        # built-in function
    
table_name.group('column_name', min)        # built-in function
    
table_name.group('column_name', max)        # built-in function
    
table_name.group('column_name', np.average)  # numpy function
    
table_name.group('column_name', np.mean)     # numpy function
    
table_name.group('column_name', np.std)      # numpy function
    
table_name.group('column_name', np.median)   # numpy function
```

In [43]:
teams_and_money = nba.select('team', 'salary')
teams_and_money

team                  | salary
Los Angeles Lakers    | 23500000
Brooklyn Nets         | 23180790
New York Knicks       | 22458401
Houston Rockets       | 21436271
Miami Heat            | 20644400
Cleveland Cavaliers   | 20644400
LA Clippers           | 20068563
Brooklyn Nets         | 19754465
Sacramento Kings      | 19317326
Oklahoma City Thunder | 18995624
... (517 rows omitted)

In [47]:
# select team and salary from the nba table and call it teams_and_money
# group salaries by teams
teams_and_money = nba.select('team', 'salary')
x = teams_and_money.group('team', sum)
x.set_format([1], NumberFormatter)

team                  | salary sum
Atlanta Hawks         | 57,182,724
Boston Celtics        | 41,359,670
Brooklyn Nets         | 103,134,468
Charlotte Hornets     | 68,876,214
Chicago Bulls         | 69,857,980
Cleveland Cavaliers   | 67,757,418
Dallas Mavericks      | 76,045,171
Denver Nuggets        | 57,074,915
Detroit Pistons       | 43,963,633
Golden State Warriors | 74,947,574
... (22 rows omitted)

In [48]:
#How many NBA players were there in each of the five positions?
nba.select('position').group('position')

position | count
C        | 97
F        | 43
G        | 49
PF       | 93
PG       | 78
SF       | 79
SG       | 88

In [49]:
#  What was the average salary of the players at each of the five positions?
positions_and_money = nba.select('position', 'salary')
positions_and_money.group('position', np.mean)

position | salary mean
C        | 4.52468e+06
F        | 3.10895e+06
G        | 4.13679e+06
PF       | 4.15431e+06
PG       | 3.96889e+06
SF       | 3.65802e+06
SG       | 3.37298e+06

# Grouping more than one column
You can group the elements of two columns using the group method.
```
table.group(['column1', 'column2'])  # result in counts for unique combinations
table.group(['column1', 'column2'], function) # finds the function of each unique combination
```
There is another method to create a contingency table of two columns it is called Pivot.  To find the pivot use the code below.  The pivot always takes two column labels, one to determine the columns and one to determine the rows.
```
table_name.pivot('column1', 'column2', values = 'column3', collect = function)
```
The functions are the same ones mentioned for the group method.

In [50]:
# create a table
more_cones = Table().with_columns(
    'Flavor', make_array('strawberry', 'chocolate', 'chocolate', 'strawberry', 'chocolate', 'bubblegum'),
    'Color', make_array('pink', 'light brown', 'dark brown', 'pink', 'dark brown', 'pink'),
    'Price', make_array(3.55, 4.75, 5.25, 5.25, 5.25, 4.75)
)

more_cones

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

In [51]:
# group and show the count
more_cones.group(['Flavor', 'Color'])

Flavor     | Color       | count
bubblegum  | pink        | 1
chocolate  | dark brown  | 2
chocolate  | light brown | 1
strawberry | pink        | 2

In [53]:
# group and show the sum
more_cones.group(['Flavor', 'Color'],sum)

Flavor     | Color       | Price sum
bubblegum  | pink        | 4.75
chocolate  | dark brown  | 10.5
chocolate  | light brown | 4.75
strawberry | pink        | 8.8

In [54]:
# group and show the mean price
more_cones.group(['Flavor', 'Color'],np.mean)

Flavor     | Color       | Price mean
bubblegum  | pink        | 4.75
chocolate  | dark brown  | 5.25
chocolate  | light brown | 4.75
strawberry | pink        | 4.4

In [55]:
# Pivot and show sum of price in contingency table
more_cones.pivot('Flavor', 'Color', values='Price', collect =sum)

Color       | bubblegum | chocolate | strawberry
dark brown  | 0         | 10.5      | 0
light brown | 0         | 4.75      | 0
pink        | 4.75      | 0         | 8.8

In [56]:
# Pivot and show mean price
more_cones.pivot('Flavor', 'Color', values='Price', collect =np.mean)

Color       | bubblegum | chocolate | strawberry
dark brown  | 0         | 5.25      | 0
light brown | 0         | 4.75      | 0
pink        | 4.75      | 0         | 4.4

In [58]:
#  Read in educ_inc.ccsv to table full_table variable and display it 
full_table = Table.read_table('educ_inc.csv')
full_table

Year        | Age       | Gender | Educational Attainment         | Personal Income     | Population Count
1/1/08 0:00 | 00 to 17  | Male   | College, less than 4-yr degree | C: 10,000 to 14,999 | 1304
1/1/08 0:00 | 00 to 17  | Female | College, less than 4-yr degree | B: 5,000 to 9,999   | 1565
1/1/08 0:00 | 65 to 80+ | Male   | College, less than 4-yr degree | A: 0 to 4,999       | 1923
1/1/08 0:00 | 65 to 80+ | Female | No high school diploma         | H: 75,000 and over  | 1981
1/1/08 0:00 | 00 to 17  | Female | No high school diploma         | D: 15,000 to 24,999 | 2009
1/1/08 0:00 | 00 to 17  | Male   | No high school diploma         | F: 35,000 to 49,999 | 2227
1/1/08 0:00 | 00 to 17  | Male   | No high school diploma         | E: 25,000 to 34,999 | 2606
1/1/08 0:00 | 00 to 17  | Male   | College, less than 4-yr degree | D: 15,000 to 24,999 | 3465
1/1/08 0:00 | 00 to 17  | Male   | No high school diploma         | D: 15,000 to 24,999 | 3974
1/1/08 0:00 | 18 to 64  | Female | No high school diploma         | H: 75,000 and over  | 4233
... (1016 rows omitted)

In [59]:
#  Read educ_inc.csv table into full_table variable 
# Select Year equal to '1/1/14 0:00'
# Age not equal to  '00 to 17'
# Assign it to variable ca_2014
#
ca_2014 = full_table.where('Year', are.equal_to('1/1/14 0:00')).where('Age', are.not_equal_to('00 to 17'))
ca_2014

Year        | Age       | Gender | Educational Attainment         | Personal Income     | Population Count
1/1/14 0:00 | 18 to 64  | Female | No high school diploma         | H: 75,000 and over  | 2058
1/1/14 0:00 | 65 to 80+ | Male   | No high school diploma         | H: 75,000 and over  | 2153
1/1/14 0:00 | 65 to 80+ | Female | No high school diploma         | G: 50,000 to 74,999 | 4666
1/1/14 0:00 | 65 to 80+ | Female | High school or equivalent      | H: 75,000 and over  | 7122
1/1/14 0:00 | 65 to 80+ | Female | No high school diploma         | F: 35,000 to 49,999 | 7261
1/1/14 0:00 | 65 to 80+ | Male   | No high school diploma         | G: 50,000 to 74,999 | 8569
1/1/14 0:00 | 18 to 64  | Female | No high school diploma         | G: 50,000 to 74,999 | 14635
1/1/14 0:00 | 65 to 80+ | Male   | No high school diploma         | F: 35,000 to 49,999 | 15212
1/1/14 0:00 | 65 to 80+ | Male   | College, less than 4-yr degree | B: 5,000 to 9,999   | 15423
1/1/14 0:00 | 65 to 80+ | Female | Bachelor's degree or higher    | A: 0 to 4,999       | 15459
... (117 rows omitted)

# Joining Tables
Some times you come across data that is stored in two tables.  One table has some of the information you want and another table has other information you want.  In tha case you must connect the table to get the information from both tables.  Each table has a column in common.  It may or may not have the same name.  Use the format below to join the tables.
```
table1.join(table1_column_for_joining, table2, table2_column_for_joining)
```

In [67]:
# Create a table of ice creams called cones
cones = Table().with_columns(
    'Flavor', make_array('strawberry', 'vanilla', 'chocolate', 'strawberry', 'chocolate'),
    'Price', make_array(3.55, 4.75, 6.55, 5.25, 5.75)
)
cones

Flavor     | Price
strawberry | 3.55
vanilla    | 4.75
chocolate  | 6.55
strawberry | 5.25
chocolate  | 5.75

In [68]:
ratings = Table().with_columns(
    'Kind', make_array('strawberry', 'chocolate', 'vanilla'),
    'Stars', make_array(2.5, 3.5, 4)
)
ratings

Kind       | Stars
strawberry | 2.5
chocolate  | 3.5
vanilla    | 4

In [69]:
rated = cones.join('Flavor', ratings, 'Kind')
rated

Flavor     | Price | Stars
chocolate  | 6.55  | 3.5
chocolate  | 5.75  | 3.5
strawberry | 3.55  | 2.5
strawberry | 5.25  | 2.5
vanilla    | 4.75  | 4

In [70]:
rated.with_column('$/Star', rated.column('Price')/rated.column('Stars')).sort(3)

Flavor     | Price | Stars | $/Star
vanilla    | 4.75  | 4     | 1.1875
strawberry | 3.55  | 2.5   | 1.42
chocolate  | 5.75  | 3.5   | 1.64286
chocolate  | 6.55  | 3.5   | 1.87143
strawberry | 5.25  | 2.5   | 2.1

In [71]:
ratings

Kind       | Stars
strawberry | 2.5
chocolate  | 3.5
vanilla    | 4

In [72]:
ratings.join('Kind', cones, 'Flavor')

Kind       | Stars | Price
chocolate  | 3.5   | 6.55
chocolate  | 3.5   | 5.75
strawberry | 2.5   | 3.55
strawberry | 2.5   | 5.25
vanilla    | 4     | 4.75

In [73]:
reviews = Table().with_columns(
    'Flavor', make_array('vanilla', 'chocolate', 'vanilla', 'chocolate'),
    'Stars', make_array(5, 3, 5, 4)
)
reviews

Flavor    | Stars
vanilla   | 5
chocolate | 3
vanilla   | 5
chocolate | 4

In [74]:
average_review = reviews.group('Flavor', np.average)
average_review

Flavor    | Stars average
chocolate | 3.5
vanilla   | 5

In [75]:
cones.join('Flavor', average_review, 'Flavor')

Flavor    | Price | Stars average
chocolate | 6.55  | 3.5
chocolate | 5.75  | 3.5
vanilla   | 4.75  | 5

# Iterations
Sometimes we want to repeat the same code a number of times.  When we want to do this we can use a for loop.
                                                                                                   
```
for x in np.arange(5):
    print (x,"squared is", x**2)
```